# Minimal Makefile to run tests.
#
# Author: Amittai Siavava, Ke Lou

all: run

.PHONY: run

run: main.py author.py editor.py reviewer.py dbconfig.py dbconfig.ini
	@printf "Running program...\n\n"
	@python3 main.py
